name: "Create assets"

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run build script
        shell: bash
        run: |
          chmod +x ./script/build.sh
          ./script/build.sh

      - name: Zip assets
        run: |
          zip ./bin/ec-windows-amd64.zip ./bin/ec-windows-amd64.exe
          zip ./bin/ec-windows-386.zip ./bin/ec-windows-386.exe

      - name: Upload windows-amd64 binary
        id: upload-win-64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./bin/ec-windows-amd64.zip
          asset_name: ec-windows-amd64.zip
          asset_content_type: application/zip

      - name: Upload windows-386 binary
        id: upload-win-386
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./bin/ec-windows-386.zip
          asset_name: ec-windows-386.zip
          asset_content_type: application/zip
